color: null
fieldLayouts:
  2acb6121-c4e0-4190-9001-81205c3600ae:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7354acbe-1215-48b0-ad55-59c71c0b2ae6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5aa89e23-a9a9-4705-a944-3509ee3de258
        userCondition: null
handle: colour
hasTitleField: true
icon: ''
name: Colour
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
