color: null
fieldLayouts:
  fcaabd1f-178a-47cb-8811-c8cbe4adce7f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92569764-f394-4985-bfe2-ae030eeb71b7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e89e2ef-583f-4338-be67-69d181d33c89
        userCondition: null
handle: material
hasTitleField: true
icon: ''
name: Material
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
