color: null
fieldLayouts:
  c3f425b6-92bc-44b4-a5e9-83f61afbe754:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9d632a33-47a5-471e-aed5-690cae32e231 # Racket img
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7f1d6aec-4649-46b3-8229-3460e844d4ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4677365d-12ae-41e8-a958-fc8aec395241 # Grip size
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a838a5e5-3fd6-4719-9b0f-26a36e2c14d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c324bdd-c108-417c-9b09-d8b32c1a3f02 # Brand
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aac04fbf-e074-4889-8dbc-b9da45801437
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e4b9339b-979e-4a9c-9a48-3f3f4dd07b81 # Colour
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 283bad99-b2d4-4fe7-9237-c30fd15fed54
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c1a7de21-1eed-4e10-a19d-cd9046170b3f # Material
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca6ff3af-ff60-44c3-841c-a41f08ac4c8f
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Name Racket'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 320705d5-079c-4920-86ca-9f120f760052
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d1d8ef0-fcce-4d5c-b7ab-b419f957d630 # price
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f85dfbb-970e-41e2-a0d6-2db299201c3c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8d1e0bb4-5cbf-40f7-a886-2f4b935f48e2 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 315f8cc1-63da-476f-b6b1-d3625afa93b6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b20d6ea-5d15-4aa6-82d4-3e1767733ca6
        userCondition: null
handle: racket
hasTitleField: true
icon: ''
name: Racket
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
