color: null
fieldLayouts:
  a4377670-ccc4-4c18-8988-6cf332bbf37b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-08-08T22:23:31+00:00'
            elementCondition: null
            fieldUid: 161cadb2-3346-446d-875d-fd6c12991b3c # IconImg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd352336-f5be-4b83-abe9-6b8254b068a8
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T22:00:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 804e60a3-5573-49a4-8ac4-402383725dce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-08T22:01:51+00:00'
            elementCondition: null
            fieldUid: 8d1e0bb4-5cbf-40f7-a886-2f4b935f48e2 # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 408c75b8-c622-401c-8908-9ffd71e7d8fa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f3cabb33-e6dd-4115-b73e-d24746dd8bac
        userCondition: null
handle: whyus
hasTitleField: true
icon: ''
name: whyUs
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
