altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  dfaeef71-2076-4628-9af1-12d17115e5e5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-08T22:01:54+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: eff30875-711b-4be7-8211-e3d3ea477905
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 316d7dd8-a5e8-4073-9e1d-4461cb9f22b3
        userCondition: null
fs: icon
handle: icons
name: Icons
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
