altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  257d6cc7-a7f5-45e9-b183-f5d9d9b50645:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 60308c69-e833-46c1-81a9-8a7a1bc799ee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b933ca7b-5f11-450d-9558-76da777cb9b3
        userCondition: null
fs: rackets
handle: rackets
name: rackets
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
