columnSuffix: null
handle: colour
instructions: 'This is the colour of the rackets.'
name: Colour
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showCardsInGrid: false
  showSiteMenu: true
  sources:
    - 'section:ee11a7a8-6300-4592-9dca-b3bd4bd806c9' # colour
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Entries
