columnSuffix: null
handle: description
instructions: 'Describe the racket. '
name: Description
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  purifierConfig: Default.json
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  showHtmlButtonForNonAdmins: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  tinymceConfig: Default.json
translationKeyFormat: null
translationMethod: none
type: abmat\tinymce\Field
