dateModified: 1723724518
email:
  fromEmail: r0377155@student.thomasmore.be
  fromName: Tennos
  transportType: craft\mail\transportadapters\Sendmail
fs:
  icon:
    hasUrls: true
    name: Icon
    settings:
      path: '@webroot/images/rackets'
    type: craft\fs\Local
    url: '@web/images/rackets'
  rackets:
    hasUrls: true
    name: rackets
    settings:
      path: '@webroot/images/rackets'
    type: craft\fs\Local
    url: '@web/images/rackets'
meta:
  __names__:
    3d1d8ef0-fcce-4d5c-b7ab-b419f957d630: price # price
    6bc4ca3d-46ec-4787-a459-7a855a084b10: 330x330 # 330x330
    8d1e0bb4-5cbf-40f7-a886-2f4b935f48e2: Description # Description
    9d262e41-c5f1-4b6b-a1d3-3d92ffb9a6b7: whyUs # whyUs
    9d632a33-47a5-471e-aed5-690cae32e231: 'Racket img' # Racket img
    43f96e4f-62d0-4c35-91b8-82484689ce37: Tennos # Tennos
    56b9156c-05b6-44a5-9c43-46fca068221b: 'Why Us' # Why Us
    57a48ddd-ed93-4b65-8437-b9def449fefa: Racket # Racket
    161cadb2-3346-446d-875d-fd6c12991b3c: IconImg # IconImg
    563c893a-6fe1-47f9-ae6f-086b59709523: ColorHex # ColorHex
    634eebf6-6b82-4619-befb-05ebf596fe9b: Tennos # Tennos
    667f8193-84c9-4735-a9ed-cda082179ede: 'Homepage content' # Homepage content
    782d5726-4839-47e7-afae-08fad69a7fd1: Simple # Simple
    912a555c-a843-4bed-9910-b86899ab959d: Rackets # Rackets
    1169d6eb-2e43-468f-b8ca-2c92d6e3c46c: Icon # Icon
    2077e8c8-01ba-41e3-8521-585e3e90831a: rackets # rackets
    890219be-5078-4a4f-95ec-7bc697729e41: Colour # Colour
    aa3c1e09-f907-482b-916b-c4d05396595c: Home # Home
    b4ae48da-0cdc-429e-ba67-685b2a87a51d: home # home
    b5c6d9ea-f544-413b-a191-44d468f61ae4: 'Name Racket' # Name Racket
    b86cf7fb-9296-42cb-9eff-515a2785107d: icon # icon
    bb961a92-ce1a-4385-a155-f483673296ee: Icons # Icons
    e4b9339b-979e-4a9c-9a48-3f3f4dd07b81: Colour # Colour
    e58e8103-a443-4125-983b-d74071eb21d5: 400x400 # 400x400
    e5548f30-7d04-4e05-8e75-628c064d88f1: 'Public Schema' # Public Schema
    ee11a7a8-6300-4592-9dca-b3bd4bd806c9: colour # colour
plugins:
  abm-tinymce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  abm-translationhelper:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      selectedSiteGroups:
        1:
          1: '1'
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      allowAttachments: '1'
      allowedMessageFields: null
      prependSender: 'On behalf of (your name)'
      prependSubject: 'New message from Tennos'
      successFlashMessage: 'Thank you for contacting Tennos. Your message has been sent. We will reply shortly. '
      toEmail: r0377155@student.thomasmore.be
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-tweaks:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  shortcut:
    edition: standard
    enabled: true
    schemaVersion: 2.1.1
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Tennos
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
