defaultPlacement: end
enableVersioning: true
entryTypes:
  - 890219be-5078-4a4f-95ec-7bc697729e41 # Colour
handle: colour
maxAuthors: 1
name: colour
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  43f96e4f-62d0-4c35-91b8-82484689ce37: # Tennos
    enabledByDefault: true
    hasUrls: true
    template: colour/_entry.twig
    uriFormat: 'colour/{slug}'
structure:
  maxLevels: null
  uid: b9e728ed-ae68-4efd-8b56-15f2e312ea43
type: structure
