defaultPlacement: end
enableVersioning: true
entryTypes:
  - b4ae48da-0cdc-429e-ba67-685b2a87a51d # home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  43f96e4f-62d0-4c35-91b8-82484689ce37: # Tennos
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
