defaultPlacement: end
enableVersioning: true
entryTypes:
  - 07da1d0c-ec2b-4264-b21f-aa002d861a46 # Material
handle: material
maxAuthors: 1
name: Material
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  43f96e4f-62d0-4c35-91b8-82484689ce37: # Tennos
    enabledByDefault: true
    hasUrls: true
    template: material/_entry
    uriFormat: 'material/{slug}'
structure:
  maxLevels: null
  uid: ced30114-3379-4704-892c-0353a00e772b
type: structure
